---

services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: "lubelogger"
      POSTGRES_PASSWORD: "lubepass"
      POSTGRES_DB: "lubelogger"
    volumes:
      - postgres:/var/lib/postgresql/
      - /etc/localtime:/etc/localtime:ro

  app:
    image: ghcr.io/hargata/lubelogger:latest
    restart: unless-stopped
    environment:
      POSTGRES_CONNECTION: "Host=postgres:5432;Username=lubelogger;Password=lubepass;Database=lubelogger;"
    # volumes used to keep data persistent
    volumes:
      - data:/App/data
      - keys:/root/.aspnet/DataProtection-Keys
    # expose port and/or use serving via traefik
    ports:
      - 8080:8080

volumes:
  data:
  keys:
  postgres:
